export const dummyResearchData = [
  {
    "row_number": 289,
    "PMID": 40162648,
    "Date ": "2025-07-10",
    "Journal": "The New England journal of medicine",
    "Tweet": "For patients with a history of smoking, the NEJM study (40162648) highlights smoking cessation in midlife as yielding the greatest gains in life-years free from death. Integrating aggressive CV risk reduction alongside lung cancer surveillance can meaningfully extend both cancer-free and overall survival.\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Tweet (Few shot learning)": "Midlife risk factor modification powerfully improves longevity: global data (2M+ people) show five risk factors (hypertension, hyperlipidemia, abnormal weight, diabetes, smoking) raised lifetime CVD risk to 24% (women) and 38% (men). Absence extended life by 11–14 years and CVD-free years by 10–13. Midlife BP control gave greatest CVD-free gains; smoking cessation maximized survival. \n",
    "DOI": "10.1056/NEJMoa2415879",
    "Specific Cancer type": "Lung and Bronchus Cancer",
    "Summary": "The study analyzed data from over 2 million individuals across 133 cohorts globally to assess how five classic risk factors—hypertension, hyperlipidemia, abnormal weight, diabetes, and smoking—impact lifetime cardiovascular disease (CVD) risk and overall mortality from age 50 up to 90 years. Findings showed that the presence of all five risk factors corresponded to a lifetime CVD risk of 24% in women and 38% in men, while absence of these factors was linked to an additional 10-13 years free of CVD and 11-14 years longer life expectancy. Midlife modification of hypertension (ages 55-59) yielded the greatest increase in CVD-free years, and smoking cessation in this age range provided the most additional life-years free from death. The study underscores the substantial impact of managing classic risk factors by midlife in extending cardiovascular health and overall survival.",
    "Abstract": "[{\"_\":\"Five risk factors account for approximately 50% of the global burden of cardiovascular disease. How the presence or absence of classic risk factors affects lifetime estimates of cardiovascular disease and death from any cause remains unclear.\",\"Label\":\"BACKGROUND\",\"NlmCategory\":\"BACKGROUND\"},{\"_\":\"We harmonized individual-level data from 2,078,948 participants across 133 cohorts, 39 countries, and 6 continents. Lifetime risk of cardiovascular disease and death from any cause was estimated up to 90 years of age according to the presence or absence of arterial hypertension, hyperlipidemia, underweight and overweight or obesity, diabetes, and smoking at 50 years of age. Differences in life span (in terms of additional life-years free of cardiovascular disease or death from any cause) according to the presence or absence of these risk factors were also estimated. Risk-factor trajectories were analyzed to predict lifetime differences according to risk-factor variation.\",\"Label\":\"METHODS\",\"NlmCategory\":\"METHODS\"},{\"_\":\"The lifetime risk of cardiovascular disease was 24% (95% confidence interval [CI], 21 to 30) among women and 38% (95% CI, 30 to 45) among men for whom all five risk factors were present. In the comparison between participants with none of the risk factors and those with all the risk factors, the estimated number of additional life-years free of cardiovascular disease was 13.3 (95% CI, 11.2 to 15.7) for women and 10.6 (95% CI, 9.2 to 12.9) for men; the estimated number of additional life-years free of death was 14.5 (95% CI, 9.1 to 15.3) for women and 11.8 (95% CI, 10.1 to 13.6) for men. As compared with no changes in the presence of all risk factors, modification of hypertension at an age of 55 to less than 60 years was associated with the most additional life-years free of cardiovascular disease, and modification of smoking at an age of 55 to less than 60 years was associated with the most additional life-years free of death.\",\"Label\":\"RESULTS\",\"NlmCategory\":\"RESULTS\"},{\"_\":\"The absence of five classic risk factors at 50 years of age was associated with more than a decade greater life expectancy than the presence of all five risk factors, in both sexes. Persons who modified hypertension and smoking in midlife had the most additional life-years free of cardiovascular disease and death from any cause, respectively. (Funded by the German Center for Cardiovascular Research [DZHK]; ClinicalTrials.gov number, NCT05466825.).\",\"Label\":\"CONCLUSIONS\",\"NlmCategory\":\"CONCLUSIONS\"}]",
    "Twiter Hashtags": "#lcsm, #lungcancer",
    "Twiiter accounts tagged": "@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Score": 8.17,
    "Selected": ""
  },
  {
    "row_number": 285,
    "PMID": 40454641,
    "Date ": "2025-07-10",
    "Journal": "The New England journal of medicine",
    "Tweet": "For PIK3CA-mutated, HR+/HER2− advanced breast cancer progressing within 12 months of adjuvant endocrine therapy, adding inavolisib to palbociclib-fulvestrant extends median OS by 7 months and doubles response rates. Vigilant toxicity monitoring—especially for hyperglycemia and mucositis—is essential for safe integration.\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Tweet (Few shot learning)": "INAVO120: Adding inavolisib to palbociclib–fulvestrant in PIK3CA-mut HR+/HER2- MBC improved median OS by 7 months (HR 0.67; ORR 62.7% vs 28%). AE profile requires proactive management. Is your clinic ready to integrate this evolving standard for early endocrine relapse?\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "DOI": "10.1056/NEJMoa2501796",
    "Specific Cancer type": "Lung and Bronchus Cancer",
    "Summary": "The phase 3 INAVO120 trial evaluated inavolisib plus palbociclib-fulvestrant versus placebo plus palbociclib-fulvestrant in patients with PIK3CA-mutated, hormone receptor-positive, HER2-negative locally advanced or metastatic breast cancer who relapsed during or within 12 months of adjuvant endocrine therapy. Among 325 patients randomized, inavolisib treatment significantly improved median overall survival (34.0 vs. 27.0 months; HR 0.67; P=0.02) and objective response rate (62.7% vs. 28.0%; P<0.001). The updated progression-free survival hazard ratio was 0.42. Adverse events such as hyperglycemia, stomatitis, gastrointestinal, and ocular toxicities were more common with inavolisib, leading to drug discontinuation in 6.8% of patients. This study demonstrates a meaningful survival benefit with inavolisib addition but with increased manageable toxicities.",
    "Abstract": "[{\"_\":\"In the phase 3, double-blind, randomized INAVO120 trial, treatment with inavolisib plus palbociclib-fulvestrant led to a significant progression-free survival benefit, as compared with placebo plus palbociclib-fulvestrant, among patients with -mutated, hormone receptor-positive, human epidermal growth factor receptor 2 (HER2)-negative locally advanced or metastatic breast cancer who had had relapse during or within 12 months after completion of adjuvant endocrine therapy.\",\"Label\":\"BACKGROUND\",\"NlmCategory\":\"BACKGROUND\",\"i\":\"PIK3CA\"},{\"_\":\"We randomly assigned patients with -mutated, hormone receptor-positive, HER2-negative locally advanced or metastatic breast cancer who had had disease recurrence or progression during or within 12 months after completion of adjuvant endocrine therapy to receive inavolisib plus palbociclib-fulvestrant (inavolisib group) or placebo plus palbociclib-fulvestrant (placebo group). In the current report, we provide the results of the final analysis of overall survival, including updated data on efficacy and safety.\",\"Label\":\"METHODS\",\"NlmCategory\":\"METHODS\",\"i\":\"PIK3CA\"},{\"_\":\"A total of 161 patients were assigned to the inavolisib group, and 164 to the placebo group. After a median follow-up of 34.2 months in the inavolisib group and 32.3 months in the placebo group, the median overall survival was 34.0 months (95% confidence interval [CI], 28.4 to 44.8) with inavolisib and 27.0 months (95% CI, 22.8 to 38.7) with placebo (hazard ratio for death, 0.67; 95% CI, 0.48 to 0.94; P = 0.02 [prespecified boundary for statistical significance, P<0.0469]). An objective response occurred in 62.7% (95% CI, 54.8 to 70.2) of patients in the inavolisib group and 28.0% (95% CI, 21.3 to 35.6) of those in the placebo group (P<0.001). The updated hazard ratio for disease progression or death was 0.42 (95% CI, 0.32 to 0.55). Adverse events led to discontinuation of inavolisib in 6.8% of patients and discontinuation of placebo in 0.6%. The incidence of hyperglycemia, stomatitis or mucosal inflammation, gastrointestinal toxic effects (e.g., diarrhea), and ocular toxic effects (e.g., dry eye and blurred vision) was higher with inavolisib than with placebo.\",\"Label\":\"RESULTS\",\"NlmCategory\":\"RESULTS\"},{\"_\":\"Treatment with inavolisib plus palbociclib-fulvestrant led to a significant overall survival benefit, as compared with placebo plus palbociclib-fulvestrant. Hyperglycemia, stomatitis or mucosal inflammation, gastrointestinal toxic effects, and ocular toxic effects were reported more frequently with inavolisib than with placebo. (Funded by F. Hoffmann-La Roche; INAVO120 ClinicalTrials.gov number, NCT04191499.).\",\"Label\":\"CONCLUSIONS\",\"NlmCategory\":\"CONCLUSIONS\"}]",
    "Twiter Hashtags": "#lcsm, #lungcancer",
    "Twiiter accounts tagged": "@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Score": 8.1666666667,
    "Selected": ""
  },
  {
    "row_number": 279,
    "PMID": 40634781,
    "Date ": "2025-07-10",
    "Journal": "Nature medicine",
    "Tweet": "AI-based computational pathology now offers a tissue-preserving, clinically viable adjunct for EGFR mutation assessment in lung adenocarcinoma. In a real-world trial, AI reduced rapid molecular test usage by up to 43% without compromising accuracy—streamlining workflows while expanding access.\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Tweet (Few shot learning)": "AI-assisted digital pathology predicts EGFR mutation in lung adenocarcinoma with AUC up to 0.890, reducing rapid molecular tests by 43% without sacrificing accuracy. This tissue-sparing approach may streamline diagnostics and preserve sample for sequencing in community practice.\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "DOI": "10.1038/s41591-025-03780-x",
    "Specific Cancer type": "Lung and Bronchus Cancer",
    "Summary": "The publication (DOI: 10.1038/s41591-025-03780-x) reports the development and validation of an AI-based computational biomarker for detecting EGFR mutations in lung adenocarcinoma using digital H&E-stained histopathology slides. Utilizing a large international dataset (N=8,461), the model fine-tunes an open-source foundation model to achieve high clinical-grade accuracy (AUC 0.847–0.870) across diverse specimen types with strong generalizability. A prospective silent trial demonstrated real-world utility, yielding an AUC of 0.890 and enabling a reduction of up to 43% in rapid molecular testing while maintaining standard clinical performance. The study provides evidence that AI-assisted histopathology can be a tissue-preserving, cost-effective tool for EGFR mutation assessment in clinical practice.",
    "Abstract": "Artificial intelligence models using digital histopathology slides stained with hematoxylin and eosin offer promising, tissue-preserving diagnostic tools for patients with cancer. Despite their advantages, their clinical utility in real-world settings remains unproven. Assessing EGFR mutations in lung adenocarcinoma demands rapid, accurate and cost-effective tests that preserve tissue for genomic sequencing. PCR-based assays provide rapid results but with reduced accuracy compared with next-generation sequencing and require additional tissue. Computational biomarkers leveraging modern foundation models can address these limitations. Here we assembled a large international clinical dataset of digital lung adenocarcinoma slides (N = 8,461) to develop a computational EGFR biomarker. Our model fine-tunes an open-source foundation model, improving task-specific performance with out-of-center generalization and clinical-grade accuracy on primary and metastatic specimens (mean area under the curve: internal 0.847, external 0.870). To evaluate real-world clinical translation, we conducted a prospective silent trial of the biomarker on primary samples, achieving an area under the curve of 0.890. The artificial-intelligence-assisted workflow reduced the number of rapid molecular tests needed by up to 43% while maintaining the current clinical standard performance. Our retrospective and prospective analyses demonstrate the real-world clinical utility of a computational pathology biomarker.",
    "Twiter Hashtags": "#lcsm, #lungcancer",
    "Twiiter accounts tagged": "@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Score": 8.08,
    "Selected": ""
  },
  {
    "row_number": 254,
    "PMID": 40628376,
    "Date ": "2025-07-09",
    "Journal": "Gesundheitswesen (Bundesverband der Arzte des Offentlichen Gesundheitsdienstes (Germany))",
    "Tweet": "The WiZen study underscores meaningful survival gains for lung cancer patients treated at German Cancer Society–certified centers. Similar baseline profiles across cohorts support a real-world advantage, reinforcing the role of structured, specialized care in complex tumor management.\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Tweet (Few shot learning)": "Where you get treated matters. WiZen study: 5-year OS for lung cancer was notably higher in German Cancer Society (GCS)-certified hospitals centers (28% vs 16.9%). Certification linked to lower all-cause mortality and improved recurrence-free survival. What can we do to bridge this gap?\n#lcsm, #lungcancer\n@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "DOI": "10.1055/a-2624-0160",
    "Specific Cancer type": "Lung and Bronchus Cancer",
    "Summary": "The WiZen study evaluated whether treatment at German Cancer Society (GCS)-certified hospitals improves long-term survival in lung cancer patients. Analyzing data from 173,999 patients in statutory health insurance records and 35,702 patients from clinical cancer registries (2009-2017), the study found similar baseline characteristics between patients treated in certified vs. non-certified hospitals. Five-year overall survival was higher in certified centers (28.0% vs. 16.9% in SHI data; 21.4% vs. 13.6% in CCR data). Adjusted Cox regression showed modest but significant reductions in all-cause mortality (hazard ratios 0.97 and 0.85) and improved recurrence-free survival (HR 0.82) for certified centers. The study concludes treatment in GCS-certified lung cancer centers is linked to meaningful survival benefits.",
    "Abstract": "Lung cancer represents the second most frequent tumor entity worldwide with an increasing number of patients treated in specialized centers. The aim of the WiZen study was to find out whether treatment at hospitals certified by the German Cancer Society (GCS) was associated with long-term survival benefits.Data for this cohort study was derived from the largest German statutory health insurance (SHI) AOK, four regional population-based clinical cancer registries (CCR), and standardized hospital quality reports. The analyses were based on 173,999 incident lung cancer patients in the SHI dataset and 35,702 patients in the CCR dataset who received primary treatment for lung cancer (ICD-10-GM C33, C34, D38.1) between 2009 and 2017.Distributions of age, sex, comorbidities, and most tumor characteristics were similar among patients treated in certified and non-certified hospitals. The Kaplan-Meier estimator for 5-year overall survival was 28.0% for patients from certified and 16.9% from non-certified hospitals (SHI data; CCR data: 21.4% vs. 13.6%). Cox-regression adjusting for relevant confounders yielded hazard ratios of 0.97 (SHI data; 95%CI 0.94, 1.00) and 0.85 (CCR data; 95%CI 0.82, 0.88) for all-cause mortality. The adjusted hazard ratio for recurrence-free survival (CCR data, UICC stage I-III, R0 only) was 0.82 (95%CI 0.75, 0.90).The presented analyses show that treatment in certified lung cancer centers is associated with relevant survival benefits and should therefore be supported.",
    "Twiter Hashtags": "#lcsm, #lungcancer",
    "Twiiter accounts tagged": "@RManochakian, @ADesaiMD, @DrJNaidoo, @lungoncdoc, @NarjustFlorezMD",
    "Score": 8,
    "Selected": ""
  },
  {
    "row_number": 257,
    "PMID": 40627292,
    "Date ": "2025-07-09",
    "Journal": "Journal of immigrant and minority health",
    "Tweet": "For Somali and Ethiopian immigrant women, mammography rates remain among the lowest, driven by unique barriers: language, cultural silence, competing priorities, and access. In-clinic: offer trusted interpretation, address pain concerns directly, and provide visual/oral education. Community outreach led by clinicians—especially those attuned to religious expectations and culturally distinct physician roles—can meaningfully bridge the screening gap.\n#bcsm, #MedEd, #BreastCancer\n@stolaney1, @drsarahsam, @annPartridgeMD, @JAMouabbi, @maryam_lustberg",
    "Tweet (Few shot learning)": "Black immigrant women from Somalia & Ethiopia face unique barriers to mammography: access, language, cultural concerns, and competing priorities. Community-based, provider-engaged outreach with oral/visual materials can bridge gaps and reduce breast cancer disparities locally.\n#bcsm, #MedEd, #BreastCancer\n@stolaney1, @drsarahsam, @annPartridgeMD, @JAMouabbi, @maryam_lustberg",
    "DOI": "10.1007/s10903-025-01730-w",
    "Specific Cancer type": "Breast Cancer",
    "Summary": "The study explores breast cancer screening barriers and preferences among Somali and Ethiopian immigrant Black women, populations with notably low mammography rates contributing to racial disparities in breast cancer outcomes. Through focus groups conducted in native languages, key barriers identified included access issues, language needs, competing responsibilities, absence of symptoms, fear, and cultural silence. Facilitators included physician recommendations, community-shared information, and personal cancer stories. Somali participants highlighted concerns about pain and religious considerations in healthcare, while Ethiopian participants emphasized trust in physicians and preferred separation of religion from medical care. The findings underscore the importance of culturally tailored, community-engaged interventions with provider involvement and appropriate communication formats to improve mammography uptake and address disparities in these East African immigrant populations.",
    "Abstract": "Black women are diagnosed with breast cancer at later stages and have a higher cancer-related mortality rate than white women. Low mammography completion contributes to racial disparities in breast cancer. Immigrant Black women face additional barriers that compound these inequities; notably, mammography rates are among the lowest for recent immigrants. We sought to describe experiences and preferences related to breast cancer screening among Somali and Ethiopian women, two growing Black immigrant populations in our community, to inform system interventions to increase screening rates within a diverse patient population at a large, urban academic medical center. We conducted semi-structured focus groups with women who were born in Somalia or Ethiopia, had immigrated to the US, and were overdue for breast cancer screening. Each focus group discussed participant views on healthcare, breast cancer screening, and opportunities for outreach. Interviews were conducted in Somali or Amharic with a real-time certified bilingual interpreter and cultural mediator. Verbatim transcripts from audio recordings underwent constant comparison and iterative data reduction analysis by two study authors. Eleven women from Somalia participated in two Somali-speaking focus groups (SSFG) and seven women from Ethiopia participated in two Amharic-speaking focus groups (ASFG). Several themes were shared between groups related to screening barriers (e.g., access, need for interpreters, competing needs and responsibilities, lack of symptoms, silence, fear) and facilitators (e.g., physician recommendation, community information and experiences about screening, stories of people with cancer). Both groups recommended more provider presence in community outreach and recommended oral or visual materials for health communication. Themes more common among SSFG participants included an expectation of pain and consideration of religion in health. ASFG participants described a desire for more separation between religion and healthcare and emphasized the role of the doctor as a trusted source of information. This study identified barriers to screening and opportunities for developing tailored, culturally relevant interventions to improve mammography completion among East African communities in our region. Health systems must consider the unique needs of both populations for interventions to meaningfully impact screening rates and ultimately reduce disparities in breast cancer.",
    "Twiter Hashtags": "#bcsm, #MedEd, #BreastCancer",
    "Twiiter accounts tagged": "@stolaney1, @drsarahsam, @annPartridgeMD, @JAMouabbi, @maryam_lustberg",
    "Score": 8,
    "Selected": ""
  },
  {
    "row_number": 258,
    "PMID": 40627273,
    "Date ": "2025-07-09",
    "Journal": "American journal of clinical dermatology",
    "Tweet": "When managing alopecias in breast cancer patients or high-risk women, treatment choice should prioritize agents with no impact on breast cancer risk or outcomes. Familiarize your team with evidence-based recommendations for alopecia areata, androgenetic, and cicatricial alopecias in this setting—especially as breast cancer survivorship grows.\n#bcsm, #MedEd, #BreastCancer\n@stolaney1, @drsarahsam, @annPartridgeMD, @JAMouabbi, @maryam_lustberg",
    "Tweet (Few shot learning)": "Hair loss in breast cancer: Managing alopecia requires therapies that are safe for survivors and those at risk—avoid options that may impact cancer risk or outcomes. Evidence-based guidance supports nuanced, patient-centered treatment decisions in community clinics.\n#bcsm, #MedEd, #BreastCancer\n@stolaney1, @drsarahsam, @annPartridgeMD, @JAMouabbi, @maryam_lustberg",
    "DOI": "10.1007/s40257-025-00961-9",
    "Specific Cancer type": "Breast Cancer",
    "Summary": "The publication with DOI 10.1007/s40257-025-00961-9 reviews hair loss disorders affecting patients with, survivors of, and women at increased risk of breast cancer, including chemotherapy- or endocrine therapy-induced alopecia, alopecia areata, androgenetic alopecia, and cicatricial alopecias. Given that about 13.1% of women in the USA develop breast cancer, the article emphasizes the necessity of selecting alopecia treatments that do not adversely affect breast cancer risk or outcomes. It evaluates the safety of common medications for these alopecias in the context of breast cancer and offers evidence-based treatment recommendations while identifying areas needing further research.",
    "Abstract": "Patients with, survivors of, and women at increased risk of breast cancer may experience various hair loss disorders, including those related to cancer treatments (such as chemotherapy- or endocrine therapy-induced alopecia), alopecia areata, androgenetic alopecia, and cicatricial alopecias. In the USA, approximately 1 in 8 women (13.1%) will develop breast cancer during their lifetime, emphasizing the importance of understanding safe treatment options for this population. Management of scarring and nonscarring alopecias in patients with or those at high risk of breast cancer requires the selection of therapies that do not impact breast cancer risk, treatment, or outcomes. In this review, we examine the safety of common medications used in the treatment of alopecia areata, androgenetic alopecia, and cicatricial alopecias with regard to breast cancer. We provide evidence-based recommendations for the use of these treatments in patients with and women at elevated risk of breast cancer while highlighting areas where further research is needed.",
    "Twiter Hashtags": "#bcsm, #MedEd, #BreastCancer",
    "Twiiter accounts tagged": "@stolaney1, @drsarahsam, @annPartridgeMD, @JAMouabbi, @maryam_lustberg",
    "Score": 8,
    "Selected": ""
  },
  {
    "row_number": 262,
    "PMID": 40425168,
    "Date ": "2025-07-09",
    "Journal": "Gesundheitswesen (Bundesverband der Arzte des Offentlichen Gesundheitsdienstes (Germany))",
    "Tweet": "Rising skin cancer rates in Germany highlight UV exposure as a modifiable risk factor requiring system-level intervention. Embedding UV protection—such as visible UV indices, shaded areas, and patient education—into local climate adaptation plans creates tangible opportunities for preventive oncology in practice.\n#cancerprevention, #cancerawareness\n@lpetrillz, @mattgonzalesmd, @crisbergerot, @RyanNipp, @NicoleStoutPT, @ramsedhom, @maryam_lustberg, @DrN_CancerPCP, @DrNicolasHart\n\n",
    "Tweet (Few shot learning)": "Rising skin cancer rates in Germany highlight UV exposure as a modifiable risk factor requiring system-level intervention. Embedding UV protection—such as visible UV indices, shaded areas, and patient education—into local climate adaptation plans creates tangible opportunities for preventive oncology in practice.\n#cancerprevention, #cancerawareness\n@lpetrillz, @mattgonzalesmd, @crisbergerot, @RyanNipp, @NicoleStoutPT, @ramsedhom, @maryam_lustberg, @DrN_CancerPCP, @DrNicolasHart\n\n",
    "DOI": "10.1055/a-2623-3832",
    "Specific Cancer type": "Cancer prevention",
    "Summary": "The publication addresses the rising incidence of skin cancer in Germany, with over 330,000 new cases annually, primarily driven by UV radiation. Climate change is expected to increase UV exposure and heat stress, prompting the German Federal Climate Adaptation Act to mandate integration of health-focused adaptation measures at all government levels. Emphasizing collaboration among science, politics, and practice, the UV-protection colloquium highlighted the need to embed UV protection within climate adaptation strategies. Recommended municipal actions include making the UV index visible, creating shaded spaces, adjusting daily routines to avoid peak UV exposure, and launching public information campaigns. The article stresses a coordinated, integrated approach to effectively reduce UV-related health risks as part of broader climate adaptation efforts.",
    "Abstract": "Skin cancer is the most common type of cancer in Germany. Over 330,000 new cases are diagnosed every year and the trend is rising. The main risk factor for the development of skin cancer is UV radiation. Higher temperatures, more hot days, more extreme weather events as well as increase in UV radiation are expected throughout Germany in the future. The federal government has therefore passed the Federal Climate Adaptation Act, which obliges the federation, federal states and local authorities to deal with the consequences of climate change and to plan adaptation measures. Particular attention is paid to human health, with the reduction of heat stress and UV-related diseases such as skin cancer being prioritized. Priming the population should be prepared for heat and UV radiation by 2030. In order to develop effective strategies, cooperation between science, politics and practice is necessary. The UV-protection colloquium brought together various stakeholders to exchange current findings and define strategies. It was concluded that a joint commitment at all levels is necessary in order to integrate UV protection into climate adaptation strategies. Concrete suggestions for municipal UV protection included making the UV index visible, creating shaded areas, adapting daily routines to avoid UV exposure at peak times and comprehensive information campaigns. These measures can help to significantly reduce UV exposure among the public. For successful implementation, various stakeholders must cooperate to raise awareness of UV protection and protect the health of the population. It is crucial that UV protection is considered indispensable in the development of heat protection measures and is incorporated into all municipal climate adaptation strategies. An integrated approach should be developed to replace existing individual measures where appropriate.",
    "Twiter Hashtags": "#cancerprevention, #cancerawareness",
    "Twiiter accounts tagged": "@lpetrillz, @mattgonzalesmd, @crisbergerot, @RyanNipp, @NicoleStoutPT, @ramsedhom, @maryam_lustberg, @DrN_CancerPCP, @DrNicolasHart\n\n",
    "Score": 8,
    "Selected": ""
  }
];

// Transform the data to match the expected format
export const transformResearchData = (data) => {
  return data.map(item => {
    // Parse abstract if it's a JSON string
    let abstract = item.Abstract || item.abstract;
    if (typeof abstract === 'string' && abstract.startsWith('[')) {
      try {
        const parsedAbstract = JSON.parse(abstract);
        abstract = parsedAbstract.map(section => section._).join(' ');
      } catch (e) {
        // If parsing fails, keep the original string
        console.warn('Failed to parse abstract JSON:', e);
      }
    }

    return {
      pmid: item.PMID?.toString() || item.row_number?.toString(),
      date: item["Date "] || item.date,
      journal: item.Journal || item.journal,
      tweet: item.Tweet || item.tweet,
      "Tweet (Few shot learning)": item["Tweet (Few shot learning)"],
      doi: item.DOI || item.doi,
      cancerType: item["Specific Cancer type"] || item.cancerType,
      summary: item.Summary || item.summary,
      abstract: abstract,
      twitterHashtags: item["Twiter Hashtags"] || item.twitterHashtags,
      twitterAccounts: item["Twiiter accounts tagged"] || item.twitterAccounts,
      score: item.Score || item.score
    };
  });
}; 